export const HOME_ROUTE = { url: '/', label: 'Home' }
export const ABOUT_ROUTE = { url: '/about', label: 'About' }
export const LOGIN_ROUTE = { url: '/login', label: 'Login' }
export const SIGN_UP_ROUTE = { url: '/sign-up', label: 'Sign Up' }
export const LOGOUT_ROUTE = { url: '/logout', label: 'Logout' }
export const CODES_HOME = { url: '/codes', label: 'Codes Space' }
export const CODES_WORKSPACE = {url: '/codes/:id' }
export const RECIPES_HOME =  { url: '/cooking-recipes', label: 'Cooking Recipes' }
export const RECIPES_SHEET = { url: '/cooking-recipes/:id' }
